export type Finished = {
  id: number;
  workoutsId: number;
  executionDay: string;
  distance: number | null;
  duration: number | null;
  pace: string | null;
  link: string | null;
  rpe: number | null;
  trimp: string | null;
  review: boolean | null;
  comments: string | null;
  feedback: string | null;
  unrealized: boolean;
  outdoor: boolean;
  intensities: string[] | null;
  unitMeasurement: string | null;
  typeWorkout: string | null;
  checkList: number[];
  distanceInMeters: number | null;
  durationInSeconds: number | null;
  paceInSeconds: number | null;
  createdAt: Date;
  updatedAt: Date;
};

export type FinishedHistory = {
  id: number;
  workoutId: number | null;
  distance: number | null;
  duration: number | null;
  pace: number | null;
  link: string | null;
  rpe: number | null;
  trimp: number | null;
  review: string | null;
  comments: string;
  feedback: string | null;
  unrealized: boolean;
  intensities: string | null;
  unitmeasurement: string | null;
  typeWorkout: string | null;
  distanceInMeters: number | null;
  durationInSeconds: number | null;
  paceInSeconds: number | null;
  createdAt: string;
  updatedAt: string;
  executionDay: string;
  outdoor: boolean;
  checkList: string | null;
  workoutsId: string | null;
  coolDownDuration: number | null;
  coolDownIntensities: string | null;
  warmUpDuration: number | null;
  warmUpIntensities: string | null;
  trainingName: string;
  trainingSubtitle: string;
  trainingDesc: string;
  trainingRunninge: boolean;
  trainingDatePublished: string | null;
  trainingId: string;
  programName: string;
  type: number;
  goal: string;
  pv: string | null;
  programpace: string | null;
  difficulty: string;
  month: string | null;
  programId: number;
};
