export type Program = {
  id: number;
  customerId: number;
  startDate: Date;
  endDate: Date;
  active: boolean;
  name: string | null;
  goal: string;
  difficultyLevel: string | null;
  referenceMonth: Date;
  pv: string | null;
  pace: string | null;
  vlan: string | null;
  paceVlan: string | null;
  vla: string | null;
  paceVla: string | null;
  vlanLevel: number;
  vlaLevel: number;
  createdAt: Date;
  updatedAt: Date;
  test: string | null;
  warningPdf: string | null;
  dateTest: Date;
  fcmValue: number | null;
  hide: boolean;
  vs2: boolean;
  additionalInformation: string;
  type: number | null;
};
